name: fortuna
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  path: ^1.9.1
  get_it: ^9.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/home/
    - assets/images/nav/
    - assets/images/squad/
    - assets/images/training/
    - assets/images/diary/
    - assets/images/
